config/routes.rb
Rails.application.routes.draw do
  get 'friendships/create'
  get 'friendships/destroy'
  resources :user_stocks
  get 'my_portfolio' , to:'users#my_portfolio'
  get 'search_stock', to: "stocks#search"

  devise_for :users
  root "welcomes#index"
  get 'welcomes/index'
  get 'my_friend', to: "users#my_friends"
  get 'search_friend', to:"users#search"
  resources :friendships
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend,class_name:'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
	has_many :user_stocks
	has_many :users, through: :user_stocks

	validates :name, :ticker, presence:true
	def self.new_lookup(ticker_symbol)
		client = IEX::Api::Client.new(publishable_token: 'pk_fae3a04c38234742b26d8bedee0999f9',
  		
  				endpoint: 'https://cloud.iexapis.com/v1')
		begin	
		   new(name:client.company(ticker_symbol).company_name,last_price:client.quote(ticker_symbol).latest_price,ticker:ticker_symbol)
		#client.quote(ticker_symbol).latest_price
        rescue
        	return nil
        end	
	end
    def self.check_stock(ticker_symbol)
		where(ticker:ticker_symbol).first
	end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends ,through: :friendships
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def under_stock_limit?
    stocks.count<=10
  end 
  def can_track_stock?(ticker_symbol)
     under_stock_limit? && !already_tracked_stock?(ticker_symbol)
  end 
  def already_tracked_stock?(ticker_symbol)
     stock=Stock.check_stock(ticker_symbol)
     return false unless stock
     stocks.where(id:stock.id).exists?
  end 
  def full_name
     return "#{first_name}#{last_name}" 
  end 
  def self.matches(field_param,param)
     where("#{field_param} like?","%#{param}%")
  end  
  def self.first_name_matches(param)
    matches('first_name',param)
  end

  def self.last_name_matches(param)
    matches('last_name',param)
  end

  def self.email_matches(param)
    matches('email',param)
  end

  def self.search(param)
    param.strip!
    serach_result= (first_name_matches(param) +last_name_matches(param)+email_matches(param)).uniq
    return nil unless serach_result
    serach_result
  end
   def except_current_user(users)
    users.reject{|user| user.id==self.id}
  end
   def not_friend_with?(id_of_friend)
    !friends.where(id:id_of_friend).exists?
  end
       
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name,:last_name])
	end
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
	end


end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following friend"
    else
      flash[:alert] = "There was something wrong with the tracking request"
    end
    redirect_to my_friend_path
  end

  def destroy
    friendship=current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice]="Successfully Unfriend"
    redirect_to my_friend_path

  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	def search
		if params[:stock].present?
			@stock=Stock.new_lookup(params[:stock])
			if @stock
            #respond_to do |format|
             #  format.js {render partial:'users/result'}
            #end

				render 'users/my_portfolio'
         else
            	flash[:alert]="Kindly provide the vaild ticker symbol:"
            	render 'users/my_portfolio'
         end 
      else
           flash[:alert]="Kindly provide some ticker name:"    	
           render 'users/my_portfolio'
        end 
    end 
end        
           

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
	def create
		   stock=Stock.new_lookup(params[:ticker])
		   @user_stock=UserStock.create(user:current_user,stock:stock)
		   flash[:notice]="Stocks has been inserted in myportfolio"
		   redirect_to my_portfolio_path
		
	   ''' else
		  flash[:notice]="Stocks already available"
		  redirect_to my_portfolio_path
	    end	'''
	end
	def destroy
		stock=Stock.find(params[:id])
		del_stock=UserStock.where(user_id:current_user.id,stock_id:stock.id).last 
	    del_stock.destroy
	    flash[:notice]="Associated stock has been removed"
	    redirect_to my_portfolio_path
	
	
	end	
end
=begin
user = User.first
	--> user.stocks
	--> stock=Stock.find(1)
	--> UserStock.all
	-->UserStock.where(user_id: user.id,stock_id:stock.id).first
	-->UserStock.where(user_id: user.id,stock_id:stock.id).first.destroy'''
=end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stock=current_user.stocks
  end
  def my_friends
    @friends=current_user.friends 
    @friends=current_user.except_current_user(@friends)

  end  
   def show
    @user = User.find(params[:id])
    @tracked_stock = @user.stocks
  end
  def search 
    if params[:friend].present?
      @friends=User.search(params[:friend])
      if @friends 
        render 'users/my_friends'
      else
        flash[:alert]="Kindly provide some valid keyword:"
        render 'users/my_friends'
      end
    else
      flash[:alert]="Kindly provide some keyword name:"
      render 'users/my_friends'
    end
  end     
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_friend.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Email:</th>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
       <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% if @friends %>
  	  <% @friends.each do |friend| %>
      <tr>
        <th scope="row"><%=friend.email%></th>
        <th scope="row"><%=friend.first_name%></th>
        <td><%=friend.last_name%></td>
       
        <td><%= button_to "Unfriend?",friendship_path(friend), method: :delete, data:{confirm:"Are you sure"}, class:"btn btn-danger"  %>
</td>
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

app/views/layouts/_friend_stock.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">s.no</th>
      <th scope="col">Company Name</th>
      <th scope="col">Price</th>
      <th scope="col">Ticker</th>
        <% if current_user.id == @user.id %>
       <th scope="col">Action</th>
       <%end%>
    </tr>
  </thead>
  <tbody>
    <% if @tracked_stock %>
  	  <% @tracked_stock.each do |stock| %>
      <tr>
        <th scope="row"><%=stock.id%></th>
        <th scope="row"><%=stock.name%></th>
        <td><%=stock.ticker%></td>
        <td><%=stock.last_price%></td>
        
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

app/views/layouts/_stock.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">s.no</th>
      <th scope="col">Company Name</th>
      <th scope="col">Price</th>
      <th scope="col">Ticker</th> 
       <th scope="col">Action</th>
      
    </tr>
  </thead>
  <tbody>
    <% if @tracked_stock %>
  	  <% @tracked_stock.each do |stock| %>
      <tr>
        <th scope="row"><%=stock.id%></th>
        <th scope="row"><%=stock.name%></th>
        <td><%=stock.ticker%></td>
        <td><%=stock.last_price%></td>
        <td><%= button_to "Remove", user_stock_path(stock), method: :delete, data:{confirm:"Are you sure"}, class:"btn btn-danger"  %>
</td>
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <%= render 'welcomes/navbar' %>
    <%= yield %>
      



       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

</div>


</html>

app/views/users/_result.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">s.no</th>
      <th scope="col">Company Name</th>
      <th scope="col">Price</th>
      <th scope="col">Ticker</th> 
       <th scope="col">Action</th>
      
    </tr>
  </thead>
  <tbody>
    <% if @tracked_stock %>
  	  <% @tracked_stock.each do |stock| %>
      <tr>
        <th scope="row"><%=stock.id%></th>
        <th scope="row"><%=stock.name%></th>
        <td><%=stock.ticker%></td>
        <td><%=stock.last_price%></td>
        <td><%= button_to "Remove", user_stock_path(stock), method: :delete, data:{confirm:"Are you sure"}, class:"btn btn-danger"  %>
</td>
      </tr>
      <% end %>
    <%end%>
  </tbody>
</table>

app/views/users/my_friends.html.erb
<h1>My Friends </h1>
<div>
	<%= form_tag search_friend_path, method: :get do |form| %>
		<div class="row">
			<div class="col-9">
				<%= text_field_tag :friend, params[:friend], placeholder:"Enter your friends here", class:"form-control" %>
			</div>
			<div class="col-3">
				<%= button_tag type: :submit, class:"btn btn-success" do  %>
					<%= 'Search'%>
				<%end%>
			</div>
		</div>
	<% end %>
</div>
<div class="row">
	<div class="col-9">
		<table class="table able-striped mt-4">
			<thead>
				<tr>
			      <th scope="col">Email:</th>
			      <th scope="col">Full Name</th>
			      <th scope="col">Actions</th>
		    	</tr>
			</thead>
			<tbody>
<% if @friends %>
<div class= "mt-5">
				
				<% @friends.each do |friend| %>
				<tr>
					<th><%=friend.email %></th>
					<th><%=friend.full_name%></th>
					<th>
					<% if current_user.not_friend_with?(friend.id) %>	
						<%= link_to 'Follow friend ?',friendships_path(friend: friend), class:"btn btn-success ml-4", method: :post %>
					<%else%>
						<div class="badge text-bg-secondary">already friend</div>
					<%end%>
						<%= link_to 'View friends ?',user_path(friend), class:"btn btn-success ml-4" %>

					</th>
				</tr>
				<% end %>		
			</div>
			<%end%>
		</tbody>
		</table>
	</div>
</div>


<% if @friends %>
    <%= render 'layouts/friend' %>
<%end%>    

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div>
	<h3>Search Ticker Here</h3>
	<%= form_tag search_stock_path, method: :get do |form| %>
		<div class="row">
			<div class="col-9">
				<%= text_field_tag :stock, params[:stock], placeholder:"Enter your ticker here", class:"form-control" %>
			</div>
			<div class="col-3">
				<%= button_tag type: :submit, class:"btn btn-success" do  %>
					<%= 'Search'%>
				<%end%>
			</div>
		</div>
	<% end %>
</div>
<div class="mt-5">
	<%if @stock %>
	 <strong>Name:</strong><%=@stock.name%>
	 <strong>Latest_price:</strong><%=@stock.last_price%>
	 <strong>Ticker:</strong><%=@stock.ticker%>
	 <% if current_user.can_track_stock?(@stock.ticker) %>

	 <%= link_to 'Add_to_Myportfolio',user_stocks_path(user:current_user,ticker:@stock.ticker), class:"btn btn-success ml-4",method: :post %>
	 <% else %>
			<p>Already tracked</p>
			<% if current_user.under_stock_limit?%>
				<p>this stocks</p>
			<%else%>
				<p>10 stocks</p>
			<%end%>
		<%end%>

	 <%end%>
	</div>
<div  id="results">
</div>

	<%=render 'layouts/stock'%>

	

app/views/users/show.html.erb
<h2>User Details</h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td><strong>First Name: </strong> <%= @user.first_name %></td>
        <td><strong>Last Name: </strong> <%= @user.last_name %></td>
       
          <% if current_user.not_friend_with?(@user.id) %>
            <%= link_to 'Follow friend?', friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-secondary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<% if !@tracked_stock.empty? %>
  <%= render 'layouts/friend_stock'%>
<% else %>
  <p class='lead'>This user is not tracking any stocks</p>
<% end %>
<%= link_to 'Back', my_friend_path, class: "btn btn-primary" %>

app/views/welcomes/_navbar.html.erb
       <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Finance-Tracker',root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'My Protfolio', my_portfolio_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "My friends", my_friend_path, class:"nav-link"  %>

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <%= link_to "Edit User", edit_user_registration_path, class:"dropdown-item" %>
            <%= link_to "New User", new_user_registration_path, class:"dropdown-item" %>
            <li><hr class="dropdown-divider"></li>
            <%= link_to "Delete User", cancel_user_registration_path, class:"dropdown-item" %>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      
      <form class="d-flex" role="search">
       <% if current_user %>
        <div class="p-2">  

        <%= current_user.full_name %>

      </div>
      <%end%>
      
      <div class="p-2">

        <%= link_to 'Logout',destroy_user_session_path,method: :delete, class:"nav-link btn btn-warning" %>
      </div>
  
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/welcomes/index.html.erb
<h1>Welcomes#index</h1>
<p>Find me in app/views/welcomes/index.html.erb</p>
<%= button_to 'Sign Out', destroy_user_session_path,method: :delete %>